# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-14 04:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ssms.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Both',
            fields=[
                ('b_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Veg+Non Veg Grub Id')),
                ('veg_venue', models.CharField(choices=[(b'VKB Mess', b'VKB Mess'), (b'KG Mess', b'KG Mess'), (b'RP Mess', b'RP Mess')], max_length=16, verbose_name='Veg Location')),
                ('non_veg_venue', models.CharField(choices=[(b'VKB Mess', b'VKB Mess'), (b'KG Mess', b'KG Mess'), (b'RP Mess', b'RP Mess')], max_length=16, verbose_name='Non Veg Location')),
                ('veg_price', models.IntegerField(default=0, verbose_name='Veg Price')),
                ('non_veg_price', models.IntegerField(default=0, verbose_name='Non Veg price')),
                ('veg_images', models.ImageField(upload_to=ssms.models.content_album_name2, verbose_name='Veg Meal Image')),
                ('non_veg_images', models.ImageField(upload_to=ssms.models.content_album_name2, verbose_name='Non Veg Image')),
            ],
        ),
        migrations.CreateModel(
            name='Grub',
            fields=[
                ('gm_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Grub UUID')),
                ('name', models.CharField(max_length=32, verbose_name='Grub Name')),
                ('meal', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg'), ('Both', 'Both')], default='Veg', max_length=16, verbose_name='Meal Type')),
                ('reg_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Registration Date')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('deadline', models.DateField(default=datetime.datetime.now)),
                ('deadline2', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=128)),
                ('excel', models.FileField(upload_to=ssms.models.content_album_name)),
                ('mails', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Grub_Coord',
            fields=[
                ('cg_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Coordinator UUID')),
                ('cg_name', models.CharField(max_length=32, verbose_name='Coordinator Name')),
                ('cg_bitsid', models.CharField(max_length=32, unique=True, verbose_name='Coordinator Bits ID')),
                ('assoc_name', models.CharField(max_length=64, verbose_name='Association')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=32)),
                ('date', models.DateTimeField(auto_now=True)),
                ('reg_by', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grub_Student',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Student Id')),
                ('name', models.CharField(max_length=32)),
                ('student_id', models.CharField(max_length=32, verbose_name='Bits Id')),
                ('user_id', models.CharField(db_index=True, max_length=32, verbose_name='Bits Email Id')),
                ('mail', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128)),
                ('meal', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], default='Veg', max_length=16, verbose_name='Mealtype Selected')),
                ('status', models.CharField(choices=[('Signed Up', 'Signed Up'), ('Opted Out', 'Opted Out')], max_length=128)),
                ('room', models.CharField(default='303', max_length=32, verbose_name='Room No.')),
                ('bhawan', models.CharField(default='VK', max_length=32, verbose_name='Bhawan')),
                ('gm_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ssms.Grub', verbose_name='Grub Id')),
            ],
        ),
        migrations.CreateModel(
            name='NonVeg',
            fields=[
                ('n_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Non Veg Grub ID')),
                ('n_venue', models.CharField(choices=[(b'VKB Mess', b'VKB Mess'), (b'KG Mess', b'KG Mess'), (b'RP Mess', b'RP Mess')], max_length=16, verbose_name='Non Veg Location')),
                ('n_price', models.IntegerField(default=0, verbose_name='Non Veg Price')),
                ('n_images', models.ImageField(upload_to=ssms.models.content_album_name2, verbose_name='Non Veg Meal image')),
                ('gm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssms.Grub', verbose_name='Grub Id')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Stud Id')),
                ('name', models.CharField(max_length=32)),
                ('bits_id', models.CharField(max_length=32, unique=True, verbose_name='BITS ID')),
                ('bhawan', models.CharField(max_length=32)),
                ('room_no', models.CharField(max_length=4, verbose_name='Room No.')),
                ('user_id', models.CharField(db_index=True, max_length=32, verbose_name='Bits Email Id')),
            ],
        ),
        migrations.CreateModel(
            name='Veg',
            fields=[
                ('v_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Veg Grub ID')),
                ('v_venue', models.CharField(choices=[(b'VKB Mess', b'VKB Mess'), (b'KG Mess', b'KG Mess'), (b'RP Mess', b'RP Mess')], max_length=16, verbose_name='Veg Location')),
                ('v_price', models.IntegerField(default=0, verbose_name='Veg Price')),
                ('v_images', models.ImageField(upload_to=ssms.models.content_album_name2, verbose_name='Veg Meal image')),
                ('gm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssms.Grub', verbose_name='Grub Id')),
            ],
        ),
        migrations.AddField(
            model_name='grub',
            name='cg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssms.Grub_Coord', verbose_name='Coordinator Id'),
        ),
        migrations.AddField(
            model_name='both',
            name='gm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssms.Grub', verbose_name='Grub Id'),
        ),
        migrations.AlterUniqueTogether(
            name='grub_student',
            unique_together=set([('student_id', 'gm_id', 'status')]),
        ),
    ]
