# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-10-02 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grub_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32, verbose_name='Bits Id')),
                ('meal', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], default='Veg', max_length=16, verbose_name='Mealtype Selected')),
                ('gm_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ssms.Grub', verbose_name='Grub Id')),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='meal',
            name='breakfast',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AddField(
            model_name='meal',
            name='dinner',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AddField(
            model_name='meal',
            name='dinnergrub',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='meal',
            name='lunch',
            field=models.CharField(default='0', max_length=512),
        ),
        migrations.AddField(
            model_name='meal',
            name='lunchgrub',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='both',
            name='non_veg_venue',
            field=models.CharField(choices=[('VKB Mess', 'VKB Mess'), ('CVR Mess', 'CVR Mess'), ('RPA Mess', 'RPA Mess'), ('RB Mess', 'RB Mess'), ('SV Mess', 'SV Mess')], max_length=16, verbose_name='Non Veg Location'),
        ),
        migrations.AlterField(
            model_name='both',
            name='veg_venue',
            field=models.CharField(choices=[('VKB Mess', 'VKB Mess'), ('CVR Mess', 'CVR Mess'), ('RPA Mess', 'RPA Mess'), ('RB Mess', 'RB Mess'), ('SV Mess', 'SV Mess')], max_length=16, verbose_name='Veg Location'),
        ),
        migrations.AlterField(
            model_name='grub_student',
            name='status',
            field=models.CharField(choices=[('Signed Up', 'Signed Up'), ('Opted Out', 'Opted Out'), ('Member', 'Member')], max_length=128),
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='nonveg',
            name='n_venue',
            field=models.CharField(choices=[('VKB Mess', 'VKB Mess'), ('CVR Mess', 'CVR Mess'), ('RPA Mess', 'RPA Mess'), ('RB Mess', 'RB Mess'), ('SV Mess', 'SV Mess')], max_length=16, verbose_name='Non Veg Location'),
        ),
        migrations.AlterField(
            model_name='veg',
            name='v_venue',
            field=models.CharField(choices=[('VKB Mess', 'VKB Mess'), ('CVR Mess', 'CVR Mess'), ('RPA Mess', 'RPA Mess'), ('RB Mess', 'RB Mess'), ('SV Mess', 'SV Mess')], max_length=16, verbose_name='Veg Location'),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
