# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grub_student',
            old_name='s_id',
            new_name='student_id',
        ),
        migrations.AlterUniqueTogether(
            name='grub_student',
            unique_together=set([('student_id', 'gm_id', 'status')]),
        ),
    ]
