# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssms', '0002_auto_20160902_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='grub',
            name='mails',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Not Sent', max_length=128),
        ),
    ]
