# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssms', '0007_auto_20170422_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('grub', 'GRUB'), ('lunch', 'LUNCH'), ('dinner', 'DINNER'), ('breakfast', 'BREAKFAST')], max_length=16)),
                ('day', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='grub_student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ssms.Batch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='items',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssms.Meal'),
        ),
    ]
