# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-21 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssms', '0008_auto_20170821_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='grub',
            name='spot_signing',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=6),
        ),
    ]
