# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssms', '0010_auto_20170822_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grub_Invalid_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=32, verbose_name='Bits Id')),
                ('meal', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg')], default='Veg', max_length=16, verbose_name='Mealtype Selected')),
                ('gm_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ssms.Grub', verbose_name='Grub Id')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='grub_invalid_students',
            unique_together=set([('student_id', 'gm_id')]),
        ),
    ]
